[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "settings.test"
python_files = ["tests.py", "test_*.py"]

[tool.coverage.run]
omit = ["/usr/*"]

[tool.black]
line-length = 120
target-version = ["py310"]
extend-exclude = '''
(
  .*/migrations/.*.py
)
'''

[tool.isort]
profile = "black"

[tool.ruff]
# Archivo de configuración de Ruff.

# Esto debe ser igual en la config. de Black.
line-length = 120

# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F"]

# Ignoramos:
#   - F401 por importar cosas que no se usan.
#   - F403 por usar `from module import *`.
ignore = ["F403", "F401"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "**/migrations/*.py"
]
per-file-ignores = {}



# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py310"

