# Generated by Django 4.0.4 on 2023-08-31 18:57

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "telefonos",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("habilidades_tecnicas", models.CharField(max_length=500)),
                ("presentacion_gral", models.CharField(max_length=500)),
                ("imagen", models.FileField(upload_to="estudiantes/imagenes")),
                ("escolaridad", models.FileField(upload_to="estudiantes/escolaridades")),
                ("cv", models.FileField(upload_to="estudiantes/cv")),
            ],
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Llamado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carga_horaria", models.CharField(max_length=150)),
                ("titulo", models.CharField(max_length=150)),
                ("salario_rango_max", models.CharField(max_length=150)),
                ("salario_text", models.CharField(max_length=150)),
                ("salario_exacto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requisitos_excluyentes", models.CharField(max_length=500)),
                ("requisitos_no_excluyentes", models.CharField(max_length=500)),
                ("anio_en_curso", models.IntegerField()),
                ("creditos_minimos", models.IntegerField()),
                ("tipo_de_contrato", models.CharField(max_length=150)),
                ("tareas_a_desarrollar", models.CharField(max_length=500)),
                ("horario", models.CharField(max_length=150)),
                ("observaciones", models.CharField(max_length=500)),
                ("departamento", models.CharField(max_length=500)),
                (
                    "modalidad",
                    models.IntegerField(choices=[(0, "Presencial"), (1, "Hibrido"), (2, "Remoto")], default=0),
                ),
                (
                    "estado",
                    models.IntegerField(
                        choices=[(0, "Pendiente"), (1, "Rechazado"), (2, "Aprobado"), (3, "Pendiente modificacion")],
                        default=0,
                    ),
                ),
                ("fecha_finalizacion", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropuestaCambioLLamado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carga_horaria", models.CharField(max_length=150)),
                ("titulo", models.CharField(max_length=150)),
                ("salario_rango_max", models.CharField(max_length=150)),
                ("salario_text", models.CharField(max_length=150)),
                ("salario_exacto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requisitos_excluyentes", models.CharField(max_length=500)),
                ("requisitos_no_excluyentes", models.CharField(max_length=500)),
                ("anio_en_curso", models.IntegerField()),
                ("creditos_minimos", models.IntegerField()),
                ("tipo_de_contrato", models.CharField(max_length=150)),
                ("tareas_a_desarrollar", models.CharField(max_length=500)),
                ("horario", models.CharField(max_length=150)),
                ("observaciones", models.CharField(max_length=500)),
                ("departamento", models.CharField(max_length=500)),
                (
                    "modalidad",
                    models.IntegerField(choices=[(0, "Presencial"), (1, "Hibrido"), (2, "Remoto")], default=0),
                ),
                (
                    "estado",
                    models.IntegerField(choices=[(0, "Pendiente"), (1, "Rechazado"), (2, "Aprobado")], default=0),
                ),
                ("llamado", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="entities.llamado")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("escolaridad", models.FileField(upload_to="postulaciones/escolaridades")),
                ("cv", models.FileField(upload_to="postulaciones/cv")),
                (
                    "estudiante",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.estudiante"),
                ),
                ("llamado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.llamado")),
            ],
        ),
        migrations.CreateModel(
            name="LLamadoCarrera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carrera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.carrera")),
                ("llamado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.llamado")),
            ],
        ),
        migrations.AddField(
            model_name="llamado",
            name="carreras",
            field=models.ManyToManyField(through="entities.LLamadoCarrera", to="entities.carrera"),
        ),
        migrations.AddField(
            model_name="llamado",
            name="etiquetas",
            field=models.ManyToManyField(to="entities.etiqueta"),
        ),
        migrations.CreateModel(
            name="EstudianteCarrera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suscrito_notificaciones", models.BooleanField()),
                (
                    "creditos_obtenidos",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(450),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("carrera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.carrera")),
                (
                    "estudiante",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="entities.estudiante"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estudiante",
            name="carreras",
            field=models.ManyToManyField(through="entities.EstudianteCarrera", to="entities.carrera"),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="etiquetas",
            field=models.ManyToManyField(to="entities.etiqueta"),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="idiomas",
            field=models.ManyToManyField(to="entities.idioma"),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="loggeable",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="postulaciones",
            field=models.ManyToManyField(through="entities.Postulacion", to="entities.llamado"),
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=150)),
                (
                    "loggeable",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "loggeable",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
