# Generated by Django 4.0.4 on 2023-08-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llamado",
            name="empresa",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="entities.empresa"),
        ),
    ]
