name: Django Tests

on:
  push:
    branches:
      - prueba  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydb  # Cambia esto al nombre de tu base de datos si es diferente
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar migraciones
        run: python manage.py migrate

      - name: Ejecutar pruebas con pytest
        run: python manage.py test

