name: Django Tests

on:
  push:
    branches:
      - prueba  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - "5432:5432"

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Instalar dependencias
        run: pip install -r requirements.txt  # Asegúrate de ajustar esto a tus requisitos

      - name: Ejecutar migraciones
        run: python manage.py migrate

      - name: Ejecutar pruebas con pytest
        run: pytest -ra